# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: swift
osx_image: xcode8	

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- set -o pipefail && xcodebuild test -workspace Example/HexaColor.xcworkspace -scheme HexaColor-Example ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.0'
  | xcpretty
- pod lib lint
